CREATE TABLE `groups` (
  `ID` int(8) unsigned NOT NULL AUTO_INCREMENT,
  `Name` varchar(128) DEFAULT NULL,
  `Description` varchar(512) DEFAULT NULL,
  `IsActive` tinyint(1) DEFAULT NULL,
  `ExternalID` varchar(16) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `project_attribute_link` (
  `ProjectID` int(11) unsigned NOT NULL,
  `AttributeID` int(11) unsigned NOT NULL,
  `AttributeValue` int(11) DEFAULT NULL,
  PRIMARY KEY (`ProjectID`,`AttributeID`),
  KEY `ProjectID` (`ProjectID`),
  KEY `AttributeID` (`AttributeID`),
  CONSTRAINT `AttributeID` FOREIGN KEY (`AttributeID`) REFERENCES `project_attributes` (`ID`),
  CONSTRAINT `ProjectID` FOREIGN KEY (`ProjectID`) REFERENCES `projects` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `project_attributes` (
  `ID` int(11) unsigned NOT NULL,
  `Name` int(11) DEFAULT NULL,
  `Order` int(11) DEFAULT NULL,
  `Description` int(11) DEFAULT NULL,
  `SectionID` int(11) DEFAULT NULL,
  `SectionName` int(11) DEFAULT NULL,
  `FieldType` int(11) DEFAULT NULL,
  `DataType` int(11) DEFAULT NULL,
  `Choices` int(11) DEFAULT NULL,
  `IsRequired` int(11) DEFAULT NULL,
  `IsUpdatable` int(11) DEFAULT NULL,
  `Value` int(11) DEFAULT NULL,
  `ValueText` int(11) DEFAULT NULL,
  `ChoicesText` int(11) DEFAULT NULL,
  `AssociatedItemIDs` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `projects` (
  `ID` int(11) unsigned NOT NULL,
  `Name` varchar(200) NOT NULL DEFAULT '',
  `IsRead` tinyint(1) DEFAULT NULL,
  `Budget` int(9) DEFAULT NULL,
  `AccountID` int(11) DEFAULT NULL,
  `AccountName` varchar(256) DEFAULT NULL,
  `SponsorEmail` varchar(100) DEFAULT NULL,
  `SponsorUID` varchar(36) DEFAULT NULL,
  `SponsorName` varchar(115) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `ModifiedUID` varchar(36) DEFAULT NULL,
  `ModifiedFullName` varchar(115) DEFAULT NULL,
  `StatusModifiedDate` datetime DEFAULT NULL,
  `Description` varchar(4096) DEFAULT NULL,
  `ExpensesBudget` int(9) DEFAULT NULL,
  `ExpensesBudgetUsed` int(9) DEFAULT NULL,
  `ActualHours` int(11) DEFAULT NULL,
  `AllowProjectTime` tinyint(1) DEFAULT NULL,
  `ApproveTimeByReportsTo` tinyint(1) DEFAULT NULL,
  `BriefcasePath` varchar(125) DEFAULT NULL,
  `EndDateBaseline` datetime DEFAULT NULL,
  `Identifier` varchar(50) DEFAULT NULL,
  `PriorityID` int(11) DEFAULT NULL,
  `PriorityName` varchar(15) DEFAULT NULL,
  `IsActive` tinyint(1) DEFAULT NULL,
  `TimeBudget` int(9) DEFAULT NULL,
  `TimeBudgetUsed` int(9) DEFAULT NULL,
  `TypeCategoryID` int(11) DEFAULT NULL,
  `TypeCategoryName` varchar(15) DEFAULT NULL,
  `TypeID` int(11) DEFAULT NULL,
  `TypeName` varchar(40) DEFAULT NULL,
  `IsPrivate` tinyint(1) DEFAULT NULL,
  `IsPublic` tinyint(1) DEFAULT NULL,
  `IsPublished` tinyint(1) DEFAULT NULL,
  `IsTemplate` tinyint(1) DEFAULT NULL,
  `IsRequest` tinyint(1) DEFAULT NULL,
  `StartDateBaseline` datetime DEFAULT NULL,
  `TemplateID` int(11) DEFAULT NULL,
  `PercentComplete` int(3) DEFAULT NULL,
  `MinScheduledDate` datetime DEFAULT NULL,
  `MaxScheduledDate` datetime DEFAULT NULL,
  `MinPendingScheduleDate` datetime DEFAULT NULL,
  `MaxPendingScheduleDate` datetime DEFAULT NULL,
  `UpdateStartEnd` tinyint(1) DEFAULT NULL,
  `ScheduleHoursByPlan` tinyint(1) DEFAULT NULL,
  `AllocationEditMode` int(2) DEFAULT NULL,
  `UseRemainingHours` tinyint(1) DEFAULT NULL,
  `AlertOnEstimatedHoursExceeded` tinyint(1) DEFAULT NULL,
  `AlertOnAssignedHoursExceeded` tinyint(1) DEFAULT NULL,
  `Admin2UID` varchar(36) DEFAULT NULL,
  `Admin2FullName` varchar(115) DEFAULT NULL,
  `Admin2Email` varchar(100) DEFAULT NULL,
  `RequestWorkflowID` int(2) DEFAULT NULL,
  `ClassificationID` int(2) DEFAULT NULL,
  `ClassificationName` varchar(75) DEFAULT NULL,
  `AddContact` tinyint(1) DEFAULT NULL,
  `DateScored` datetime DEFAULT NULL,
  `AdminName` varchar(115) DEFAULT NULL,
  `AdminUID` varchar(36) DEFAULT NULL,
  `AdminEmail` varchar(100) DEFAULT NULL,
  `EndDateInitial` datetime DEFAULT NULL,
  `EndDateInitialIsNull` tinyint(1) DEFAULT NULL,
  `ExpensesBudgetInitial` tinyint(1) DEFAULT NULL,
  `StartDateInitial` datetime DEFAULT NULL,
  `StartDateInitialIsNull` tinyint(1) DEFAULT NULL,
  `BudgetInitial` int(9) DEFAULT NULL,
  `TimeBudgetInitial` int(9) DEFAULT NULL,
  `RequestStatus` varchar(40) DEFAULT NULL,
  `Requirements` varchar(256) DEFAULT NULL,
  `IntangibleBenefits` varchar(256) DEFAULT NULL,
  `CreatedUID` varchar(40) DEFAULT NULL,
  `CreatedFullName` varchar(115) DEFAULT NULL,
  `CreatedEmail` varchar(100) DEFAULT NULL,
  `StatusName` varchar(40) DEFAULT NULL,
  `ApplyMetrics` tinyint(1) DEFAULT NULL,
  `StatusComments` varchar(512) DEFAULT NULL,
  `StatusModifiedByUID` varchar(36) DEFAULT NULL,
  `StatusModifiedByFullName` varchar(75) DEFAULT NULL,
  `DeductAmount` int(9) DEFAULT NULL,
  `TimeAmount` int(9) DEFAULT NULL,
  `EstimatedHours` int(6) DEFAULT NULL,
  `EstimatedHoursInitial` int(6) DEFAULT NULL,
  `ScheduledHours` int(6) DEFAULT NULL,
  `PendingHours` int(6) DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `StatusID` int(6) DEFAULT NULL,
  `Health` int(2) DEFAULT NULL,
  `HealthName` varchar(25) DEFAULT NULL,
  `HealthDescription` varchar(100) DEFAULT NULL,
  `ReferenceType` varchar(30) DEFAULT NULL,
  `ReferenceID` int(5) DEFAULT NULL,
  `StatusDescription` varchar(100) DEFAULT NULL,
  `GoalsScore` int(3) DEFAULT NULL,
  `RisksScore` int(3) DEFAULT NULL,
  `ScorecardScore` int(3) DEFAULT NULL,
  `CompositeScore` int(3) DEFAULT NULL,
  `CompositeScorePct` int(3) DEFAULT NULL,
  `InternalTypeID` varchar(40) DEFAULT NULL,
  `PortfoliosCount` int(3) DEFAULT NULL,
  `IsBaselineSupported` tinyint(1) DEFAULT NULL,
  `IsResourceAssignmentSupported` tinyint(1) DEFAULT NULL,
  `IsTaskDetailSupported` tinyint(1) DEFAULT NULL,
  `IsTaskUpdateSupported` tinyint(1) DEFAULT NULL,
  `IsTimeEntrySupported` tinyint(1) DEFAULT NULL,
  `IsTicketToTaskConversionSupported` tinyint(1) DEFAULT NULL,
  `IsActiveOpenAndUserOnProject` tinyint(1) DEFAULT NULL,
  `IsBackupSupported` int(11) DEFAULT NULL,
  `ServiceID` int(6) DEFAULT NULL,
  `ServiceName` varchar(100) DEFAULT NULL,
  `ServiceCategoryID` int(6) DEFAULT NULL,
  `ServiceCategoryName` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_AdminUID` (`AdminUID`),
  KEY `FK_SponsorUID` (`SponsorUID`),
  KEY `FK_ModifiedUID` (`ModifiedUID`),
  KEY `FK_Admin2UID` (`Admin2UID`),
  KEY `FK_CreatedUID` (`CreatedUID`),
  KEY `FK_StatusModifiedByUID` (`StatusModifiedByUID`),
  CONSTRAINT `FK_Admin2UID` FOREIGN KEY (`Admin2UID`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_AdminUID` FOREIGN KEY (`AdminUID`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_CreatedUID` FOREIGN KEY (`CreatedUID`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_ModifiedUID` FOREIGN KEY (`ModifiedUID`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_SponsorUID` FOREIGN KEY (`SponsorUID`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_StatusModifiedByUID` FOREIGN KEY (`StatusModifiedByUID`) REFERENCES `users` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ticketattribchoice_link` (
  `attributeID` int(11) unsigned NOT NULL,
  `choiceID` int(11) unsigned NOT NULL,
  PRIMARY KEY (`attributeID`,`choiceID`),
  KEY `choiceID` (`choiceID`),
  CONSTRAINT `ticketattribchoice_link_ibfk_1` FOREIGN KEY (`attributeID`) REFERENCES `ticketattributes` (`ID`),
  CONSTRAINT `ticketattribchoice_link_ibfk_2` FOREIGN KEY (`choiceID`) REFERENCES `ticketattribute_choices` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ticketattribute_choices` (
  `ID` int(8) unsigned NOT NULL,
  `Name` varchar(128) DEFAULT NULL,
  `IsActive` tinyint(1) DEFAULT NULL,
  `CompositeDisplayName` varchar(128) DEFAULT NULL,
  `DateCreated` datetime DEFAULT NULL,
  `DateModified` datetime DEFAULT NULL,
  `Order` int(6) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ticketattributes` (
  `ID` int(8) unsigned NOT NULL,
  `AppID` int(6) DEFAULT NULL,
  `AppName` varchar(64) DEFAULT NULL,
  `Component` int(4) unsigned DEFAULT NULL,
  `Name` varchar(512) DEFAULT NULL,
  `NameWithAppName` varchar(576) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `IsProtected` tinyint(1) DEFAULT NULL,
  `ProtectionSettings` varchar(32) DEFAULT NULL,
  `IsRequired` tinyint(1) DEFAULT NULL,
  `IsUpdatable` tinyint(1) DEFAULT NULL,
  `Order` int(6) unsigned DEFAULT NULL,
  `Description` varchar(512) DEFAULT NULL,
  `IsActive` tinyint(1) DEFAULT NULL,
  `HeaderText` varchar(32) DEFAULT NULL,
  `SectionID` int(4) unsigned DEFAULT NULL,
  `SectionName` varchar(32) DEFAULT NULL,
  `ParentAttributeID` int(8) unsigned DEFAULT NULL,
  `ParentAttributeName` varchar(512) DEFAULT NULL,
  `FieldType` varchar(32) DEFAULT NULL,
  `FieldTypeFriendly` varchar(32) DEFAULT NULL,
  `DataType` varchar(16) DEFAULT NULL,
  `DataFormatString` varchar(32) DEFAULT NULL,
  `DataTypeFriendly` varchar(16) DEFAULT NULL,
  `Choices` varchar(32) DEFAULT NULL,
  `CanHaveChoices` tinyint(1) DEFAULT NULL,
  `IsMultiSelect` tinyint(1) DEFAULT NULL,
  `AssociatedItemIDs` varchar(32) DEFAULT NULL,
  `IsGlobal` tinyint(1) DEFAULT NULL,
  `Value` varchar(32) DEFAULT NULL,
  `ValueText` varchar(32) DEFAULT NULL,
  `DefaultValue` varchar(32) DEFAULT NULL,
  `CustomFormLabelText` varchar(32) DEFAULT NULL,
  `DisplayName` varchar(128) DEFAULT NULL,
  `CustomFormHelpText` varchar(32) DEFAULT NULL,
  `DisplayHelp` varchar(32) DEFAULT NULL,
  `CustomFormPlaceholderText` varchar(32) DEFAULT NULL,
  `IsClientVisible` tinyint(1) DEFAULT NULL,
  `IsMismatched` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ParentIDAttributeID` (`ParentAttributeID`),
  CONSTRAINT `FK_ParentIDAttributeID` FOREIGN KEY (`ParentAttributeID`) REFERENCES `ticketattributes` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tickets` (
  `ID` int(11) unsigned NOT NULL,
  `ParentID` int(11) unsigned DEFAULT NULL,
  `ParentTitle` varchar(64) DEFAULT NULL,
  `ParentClass` int(5) DEFAULT NULL,
  `TypeID` int(8) DEFAULT NULL,
  `TypeName` varchar(128) DEFAULT NULL,
  `TypeCategoryID` int(7) DEFAULT NULL,
  `TypeCategoryName` varchar(32) DEFAULT NULL,
  `Classification` int(5) DEFAULT NULL,
  `FormID` int(11) DEFAULT NULL,
  `FormName` varchar(256) DEFAULT NULL,
  `Title` varchar(256) DEFAULT NULL,
  `Description` varchar(1024) DEFAULT NULL,
  `Uri` varchar(32) DEFAULT NULL,
  `AccountID` int(8) DEFAULT NULL,
  `AccountName` varchar(128) DEFAULT NULL,
  `SourceID` int(3) DEFAULT NULL,
  `SourceName` varchar(128) DEFAULT NULL,
  `StatusID` int(7) DEFAULT NULL,
  `StatusName` varchar(32) DEFAULT NULL,
  `StatusClass` int(2) DEFAULT NULL,
  `ImpactID` int(3) DEFAULT NULL,
  `ImpactName` varchar(32) DEFAULT NULL,
  `UrgencyID` int(7) DEFAULT NULL,
  `UrgencyName` varchar(32) DEFAULT NULL,
  `PriorityID` int(7) DEFAULT NULL,
  `PriorityName` varchar(32) DEFAULT NULL,
  `PriorityOrder` int(3) DEFAULT NULL,
  `SlaID` int(3) DEFAULT NULL,
  `SlaName` varchar(64) DEFAULT NULL,
  `IsSlaViolated` tinyint(1) DEFAULT NULL,
  `IsSlaRespondByViolated` tinyint(1) DEFAULT NULL,
  `IsSlaResolveByViolated` tinyint(1) DEFAULT NULL,
  `RespondByDate` datetime DEFAULT NULL,
  `ResolveByDate` datetime DEFAULT NULL,
  `SlaBeginDate` datetime DEFAULT NULL,
  `IsOnHold` tinyint(1) DEFAULT NULL,
  `PlacedOnHoldDate` datetime DEFAULT NULL,
  `GoesOffHoldDate` datetime DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `CreatedUid` varchar(36) DEFAULT NULL,
  `CreatedFullName` varchar(128) DEFAULT NULL,
  `CreatedEmail` varchar(128) DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `ModifiedUid` varchar(36) DEFAULT NULL,
  `ModifiedFullName` varchar(128) DEFAULT NULL,
  `RequestorName` varchar(128) DEFAULT NULL,
  `RequestorFirstName` varchar(40) DEFAULT NULL,
  `RequestorLastName` varchar(40) DEFAULT NULL,
  `RequestorEmail` varchar(128) DEFAULT NULL,
  `RequestorPhone` varchar(15) DEFAULT NULL,
  `RequestorUid` varchar(36) DEFAULT NULL,
  `ActualMinutes` int(4) DEFAULT NULL,
  `EstimatedMinutes` varchar(10) DEFAULT NULL,
  `DaysOld` varchar(4) DEFAULT NULL,
  `StartDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `ResponsibleUid` varchar(36) DEFAULT NULL,
  `ResponsibleFullName` varchar(128) DEFAULT NULL,
  `ResponsibleEmail` varchar(128) DEFAULT NULL,
  `ResponsibleGroupID` int(8) unsigned DEFAULT NULL,
  `ResponsibleGroupName` varchar(128) DEFAULT NULL,
  `RespondedDate` datetime DEFAULT NULL,
  `RespondedUid` varchar(36) DEFAULT NULL,
  `RespondedFullName` varchar(128) DEFAULT NULL,
  `CompletedDate` datetime DEFAULT NULL,
  `CompletedUid` varchar(36) DEFAULT NULL,
  `CompletedFullName` varchar(128) DEFAULT NULL,
  `ReviewerUid` varchar(36) DEFAULT NULL,
  `ReviewerFullName` varchar(128) DEFAULT NULL,
  `ReviewerEmail` varchar(128) DEFAULT NULL,
  `ReviewingGroupID` int(8) unsigned DEFAULT NULL,
  `ReviewingGroupName` varchar(128) DEFAULT NULL,
  `TimeBudget` varchar(10) DEFAULT NULL,
  `ExpensesBudget` varchar(10) DEFAULT NULL,
  `TimeBudgetUsed` varchar(10) DEFAULT NULL,
  `ExpensesBudgetUsed` varchar(10) DEFAULT NULL,
  `IsConvertedToTask` tinyint(1) DEFAULT NULL,
  `ConvertedToTaskDate` datetime DEFAULT NULL,
  `ConvertedToTaskUid` varchar(36) DEFAULT NULL,
  `ConvertedToTaskFullName` varchar(128) DEFAULT NULL,
  `TaskProjectID` int(11) unsigned DEFAULT NULL,
  `TaskProjectName` varchar(256) DEFAULT NULL,
  `TaskPlanID` int(7) DEFAULT NULL,
  `TaskPlanName` varchar(128) DEFAULT NULL,
  `TaskID` int(11) DEFAULT NULL,
  `TaskTitle` varchar(256) DEFAULT NULL,
  `TaskStartDate` datetime DEFAULT NULL,
  `TaskEndDate` datetime DEFAULT NULL,
  `TaskPercentComplete` int(3) DEFAULT NULL,
  `OpportunityID` int(3) DEFAULT NULL,
  `OpportunityName` varchar(32) DEFAULT NULL,
  `LocationID` int(4) DEFAULT NULL,
  `LocationName` varchar(64) DEFAULT NULL,
  `LocationRoomID` int(4) DEFAULT NULL,
  `LocationRoomName` varchar(64) DEFAULT NULL,
  `RefCode` varchar(20) DEFAULT NULL,
  `ServiceID` int(8) DEFAULT NULL,
  `ServiceName` varchar(128) DEFAULT NULL,
  `ServiceCategoryID` int(8) DEFAULT NULL,
  `ServiceCategoryName` varchar(128) DEFAULT NULL,
  `ArticleID` int(8) DEFAULT NULL,
  `ArticleSubject` varchar(32) DEFAULT NULL,
  `ArticleStatus` int(3) DEFAULT NULL,
  `ArticleCategoryPathNames` varchar(64) DEFAULT NULL,
  `AppID` int(6) DEFAULT NULL,
  `Notify` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_TicketsModifiedUid` (`ModifiedUid`),
  KEY `FK_TicketsCreatedUid` (`CreatedUid`),
  KEY `FK_TicketsReviewerUid` (`ReviewerUid`),
  KEY `FK_TicketsConvertedToTaskUid` (`ConvertedToTaskUid`),
  KEY `FK_RequestorUid` (`RequestorUid`),
  KEY `FK_ResponsibleUid` (`ResponsibleUid`),
  KEY `FK_ResponsibleGroupID` (`ResponsibleGroupID`),
  KEY `FK_RespondedUid` (`RespondedUid`),
  KEY `FK_CompletedUid` (`CompletedUid`),
  KEY `FK_ReviewerUid` (`ReviewerUid`),
  KEY `FK_ReviewingGroupID` (`ReviewingGroupID`),
  KEY `FK_TaskProjectID` (`TaskProjectID`),
  CONSTRAINT `FK_CompletedUid` FOREIGN KEY (`CompletedUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_RequestorUid` FOREIGN KEY (`RequestorUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_RespondedUid` FOREIGN KEY (`RespondedUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_ResponsibleGroupID` FOREIGN KEY (`ResponsibleGroupID`) REFERENCES `groups` (`ID`),
  CONSTRAINT `FK_ResponsibleUid` FOREIGN KEY (`ResponsibleUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_ReviewerUid` FOREIGN KEY (`ReviewerUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_ReviewingGroupID` FOREIGN KEY (`ReviewingGroupID`) REFERENCES `groups` (`ID`),
  CONSTRAINT `FK_TaskProjectID` FOREIGN KEY (`TaskProjectID`) REFERENCES `projects` (`ID`),
  CONSTRAINT `FK_TicketsConvertedToTaskUid` FOREIGN KEY (`ConvertedToTaskUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_TicketsCreatedUid` FOREIGN KEY (`CreatedUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_TicketsModifiedUid` FOREIGN KEY (`ModifiedUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_TicketsReviewerUid` FOREIGN KEY (`ReviewerUid`) REFERENCES `users` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tickets_attributes_link` (
  `ticketID` int(11) unsigned NOT NULL,
  `attributeID` int(8) unsigned NOT NULL,
  `value` varchar(4096) DEFAULT NULL,
  PRIMARY KEY (`ticketID`,`attributeID`),
  KEY `attributeID` (`attributeID`),
  CONSTRAINT `tickets_attributes_link_ibfk_3` FOREIGN KEY (`ticketID`) REFERENCES `tickets` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tickets_attributes_link_ibfk_4` FOREIGN KEY (`attributeID`) REFERENCES `ticketattributes` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `timeentries` (
  `TimeID` int(11) unsigned NOT NULL,
  `ItemID` int(11) DEFAULT NULL,
  `ItemTitle` varchar(256) DEFAULT NULL,
  `InvoiceID` int(11) DEFAULT NULL,
  `StatusFullName` varchar(115) DEFAULT NULL,
  `StatusUid` varchar(36) DEFAULT NULL,
  `StatusDate` datetime DEFAULT NULL,
  `Uid` varchar(36) DEFAULT NULL,
  `CostRate` float DEFAULT NULL,
  `BillRate` float DEFAULT NULL,
  `Limited` tinyint(1) DEFAULT NULL,
  `TimeTypeID` int(11) unsigned DEFAULT NULL,
  `Billable` tinyint(1) DEFAULT NULL,
  `AppID` int(11) DEFAULT NULL,
  `AppName` varchar(100) DEFAULT NULL,
  `ModType` int(5) DEFAULT NULL,
  `Status` int(5) DEFAULT NULL,
  `TicketID` int(11) unsigned DEFAULT NULL,
  `Hours` float DEFAULT NULL,
  `Minutes` float DEFAULT NULL,
  `Description` varchar(4096) DEFAULT NULL,
  `ProjectID` int(11) unsigned DEFAULT NULL,
  `ProjectName` varchar(200) DEFAULT NULL,
  `PlanID` int(6) DEFAULT NULL,
  `TimeDate` datetime DEFAULT NULL,
  `ProjectIsActive` tinyint(1) DEFAULT NULL,
  `ApproverFullName` varchar(115) DEFAULT NULL,
  `ApproverUid` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`TimeID`),
  KEY `FK_StatusUID` (`StatusUid`),
  KEY `FK_Uid` (`Uid`),
  KEY `FK_ApproverUid` (`ApproverUid`),
  KEY `FK_TETimeTypeID` (`TimeTypeID`),
  KEY `FK_TETicketID` (`TicketID`),
  KEY `FK_TEProjectID` (`ProjectID`),
  CONSTRAINT `FK_ApproverUid` FOREIGN KEY (`ApproverUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_StatusUID` FOREIGN KEY (`StatusUid`) REFERENCES `users` (`UID`),
  CONSTRAINT `FK_TETicketID` FOREIGN KEY (`TicketID`) REFERENCES `tickets` (`ID`),
  CONSTRAINT `FK_TETimeTypeID` FOREIGN KEY (`TimeTypeID`) REFERENCES `timetypes` (`ID`),
  CONSTRAINT `FK_Uid` FOREIGN KEY (`Uid`) REFERENCES `users` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `timetypes` (
  `ID` int(11) unsigned NOT NULL,
  `Name` varchar(100) DEFAULT NULL,
  `Code` varchar(100) DEFAULT NULL,
  `GLAccount` int(11) DEFAULT NULL,
  `HelpText` varchar(512) DEFAULT NULL,
  `DefaultLimitMinutes` int(11) DEFAULT NULL,
  `IsBillable` tinyint(1) DEFAULT NULL,
  `IsCapitalized` tinyint(1) DEFAULT NULL,
  `IsLimited` tinyint(1) DEFAULT NULL,
  `IsActive` tinyint(1) DEFAULT NULL,
  `IsTimeOffTimeType` tinyint(1) DEFAULT NULL,
  `CreateScheduleEntriesForTimeOff` tinyint(1) DEFAULT NULL,
  `CreatedDate` datetime DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL,
  `IsActiveOnItem` tinyint(1) DEFAULT NULL,
  `ItemActualHours` int(11) DEFAULT NULL,
  `ItemAddedDate` datetime DEFAULT NULL,
  `ItemAddedUid` varchar(40) DEFAULT NULL,
  `ItemAddedFullName` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ItemAddedUID` (`ItemAddedUid`),
  CONSTRAINT `FK_ItemAddedUID` FOREIGN KEY (`ItemAddedUid`) REFERENCES `users` (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `users` (
  `UID` varchar(36) NOT NULL DEFAULT '',
  `BEID` varchar(36) DEFAULT NULL,
  `BEIDInt` int(3) DEFAULT NULL,
  `IsActive` tinyint(1) DEFAULT NULL,
  `UserName` varchar(100) DEFAULT NULL,
  `FullName` varchar(115) DEFAULT NULL,
  `FirstName` varchar(40) DEFAULT NULL,
  `LastName` varchar(40) DEFAULT NULL,
  `MiddleName` varchar(35) DEFAULT NULL,
  `Birthday` datetime DEFAULT NULL,
  `Salutation` varchar(10) DEFAULT NULL,
  `Nickname` varchar(128) DEFAULT NULL,
  `DefaultAccountID` int(11) DEFAULT NULL,
  `DefaultAccountName` varchar(50) DEFAULT NULL,
  `PrimaryEmail` varchar(100) DEFAULT NULL,
  `AlternateEmail` varchar(100) DEFAULT NULL,
  `ExternalID` int(7) DEFAULT NULL,
  `AlternateID` int(7) DEFAULT NULL,
  `Applications` varchar(50) DEFAULT NULL,
  `SecurityRoleName` varchar(50) DEFAULT NULL,
  `SecurityRoleID` varchar(36) DEFAULT NULL,
  `Permissions` varchar(50) DEFAULT NULL,
  `OrgApplications` varchar(25) DEFAULT NULL,
  `GroupIDs` varchar(50) DEFAULT NULL,
  `ReferenceID` int(7) DEFAULT NULL,
  `AlertEmail` varchar(100) DEFAULT NULL,
  `ProfileImageFileName` varchar(40) DEFAULT NULL,
  `Company` varchar(60) DEFAULT NULL,
  `Title` varchar(60) DEFAULT NULL,
  `HomePhone` varchar(14) DEFAULT NULL,
  `PrimaryPhone` varchar(16) DEFAULT NULL,
  `WorkPhone` varchar(14) DEFAULT NULL,
  `Pager` varchar(14) DEFAULT NULL,
  `OtherPhone` varchar(14) DEFAULT NULL,
  `MobilePhone` varchar(14) DEFAULT NULL,
  `Fax` varchar(14) DEFAULT NULL,
  `DefaultPriorityID` int(11) DEFAULT NULL,
  `DefaultPriorityName` varchar(50) DEFAULT NULL,
  `AboutMe` varchar(256) DEFAULT NULL,
  `WorkAddress` varchar(256) DEFAULT NULL,
  `WorkCity` varchar(30) DEFAULT NULL,
  `WorkState` varchar(25) DEFAULT NULL,
  `WorkZip` varchar(10) DEFAULT NULL,
  `WorkCountry` varchar(40) DEFAULT NULL,
  `HomeAddress` varchar(60) DEFAULT NULL,
  `HomeCity` varchar(30) DEFAULT NULL,
  `HomeState` varchar(25) DEFAULT NULL,
  `HomeZip` varchar(10) DEFAULT NULL,
  `HomeCountry` varchar(40) DEFAULT NULL,
  `DefaultRate` float DEFAULT NULL,
  `CostRate` float DEFAULT NULL,
  `IsEmployee` tinyint(1) DEFAULT NULL,
  `WorkableHours` int(3) DEFAULT NULL,
  `IsCapacityManaged` tinyint(1) DEFAULT NULL,
  `ReportTimeAfterDate` datetime DEFAULT NULL,
  `EndDate` datetime DEFAULT NULL,
  `ShouldReportTime` tinyint(1) DEFAULT NULL,
  `ReportsToUID` varchar(36) DEFAULT NULL,
  `ReportsToFullName` varchar(115) DEFAULT NULL,
  `ResourcePoolID` int(7) DEFAULT NULL,
  `ResourcePoolName` varchar(75) DEFAULT NULL,
  `TimeZoneID` int(2) DEFAULT NULL,
  `TimeZoneName` varchar(50) DEFAULT NULL,
  `TypeID` int(7) DEFAULT NULL,
  `AuthenticationUserName` varchar(100) DEFAULT NULL,
  `AuthenticationProviderID` int(5) DEFAULT NULL,
  `Attributes` varchar(50) DEFAULT NULL,
  `Gender` int(11) DEFAULT NULL,
  `IMProvider` varchar(25) DEFAULT NULL,
  `IMHandle` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
